server:
  port: 8080
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印语句
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.yiwang.graduate.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  freemarker:
#    template-loader-path: classpath:/templates/  没用？
    suffix: .ftl
#    prefix: classpath:/templates/      //freemarker别用这个，thymeleaf可以考虑
    content-type: text/html
    charset: UTF-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: req
    cache: false
  redis:
    port: 6379
    database: 6
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000ms
        min-idle: 10
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        #定义消费者做多同时处理10个消息
        prefetch: 10
        #消息手动确认
        acknowledge-mode: manual
  jpa:
    database: ddl-auto=create-drop